baseURL = "https://pavel-main.github.io/"
googleAnalytics = "UA-171038047-2"

theme = "soho"
title = "Pavel Kiselyov - Engineering Blog"
languageCode = "en"
enableInlineShortcodes = true
publishDir = "docs"

summarylength = 100
enableEmoji = true

[params]
author = "Pavel Kiselyov"
profilePicture = "profile_pic_border.png"
copyright = "Pavel Kiselyov"

## Set custom theme color.
themeColor = "#1e2a62"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/pavel-main"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/pavel-bc"  

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/pavel-main"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Projects"
  weight = 100
  identifier = "projects"
  url = "/projects/"  

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4
